package presentation;

//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class AddCashier extends JPanel {
	private JLabel labelUsername;
	private JTextField username;
	private JLabel labelPassword;
	private JTextField password;
	private JButton addButton;
	private JFrame frame;

	public AddCashier() {

		labelUsername = new JLabel ("Username:");
		username = new JTextField (5);
		labelPassword = new JLabel ("Password:");
		password = new JTextField (5);
		addButton = new JButton ("Add");

		frame = new JFrame("Add Cashier");
		frame.setSize(new Dimension(301, 175));

		JPanel p = new JPanel();
		p.setLayout(null);

		labelUsername.setBounds (20, 15, 100, 25);
		username.setBounds (20, 35, 100, 25);
		labelPassword.setBounds (20, 70, 100, 25);
		password.setBounds (20, 90, 100, 25);
		addButton.setBounds (165, 55, 100, 40);

		p.add (labelUsername);
		p.add (username);
		p.add (labelPassword);
		p.add (password);
		p.add (addButton);

		frame.setContentPane(p);	
		frame.setVisible(false);
	}
	public String getPassword(){
		return password.getText();
	}
	public String getUsername(){
		return username.getText();
	}
	
	public void setFrame(){
		this.frame.setVisible(true);
	}
	
	public JButton getAddButton(){
		return this.addButton;
	}

	void addListener(ActionListener listen) {
		addButton.addActionListener(listen);
	}

}
